#!/bin/sh

source $(dirname $0)/traffic_common.sh

echo -e \
"Consumed: $(($TPer + $TEph)) B 
         ($TPer B accounted to disk)
Limit:    $TMax B

Please donate $(($(($TPer + TEph)) / $BytesPerCent)) cent."