#!/bin/sh

source $(dirname $0)/traffic_common.sh	

# annoy user
echo "How many CENT have you donated to the collecting box?"
read Donation

# check value sanity
if [ "$Donation" -lt 0 ] 2>/dev/null || [ $? -eq 2 ]; then
	echo "$Donation does not look #like a sane number"
	exit -1
fi

# calc and store new value
BytesDonated=$(( $Donation * $BytesPerCent ))
TMax=$(($TMax + $BytesDonated))
echo $TMax > $TMaxFile

# TODO: log donation to some remote place

# cheer user up
echo "You have donated $((BytesDonated / 1024 / 1024)) MB." \
     "The new limit is $((TMax / 1024 / 1024)) MB."
